name: Tofu Apply
on:
  push:
    branches: ["main"]
    paths: ["td5/scripts/tofu/live/**"]  # Détecte tous les dossiers OpenTofu

jobs:
  # Job 1 : Détecter les dossiers modifiés
  detect-changes:
    name: "Détecter les dossiers modifiés"
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.changed-dirs.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-dirs.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Nécessaire pour comparer avec le commit précédent

      - name: Détecter les dossiers OpenTofu modifiés
        id: changed-dirs
        uses: tj-actions/changed-files@v44
        with:
          files: td5/scripts/tofu/live/**/  # Cherche les changements dans tous les sous-dossiers
          dir_names: true                    # Retourne les noms de dossiers, pas les fichiers
          json: true                         # Format JSON pour la matrix

  # Job 2 : Exécuter tofu apply pour chaque dossier modifié
  apply:
    name: "Tofu Apply (${{ matrix.directory }})"
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.detect-changes.outputs.directories) }}
      fail-fast: false  # Continue même si un dossier échoue
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::994077996150:role/lambda-sample-apply
          role-session-name: apply-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1

      - name: tofu apply
        id: apply
        working-directory: ${{ matrix.directory }}  # Utilise le dossier de la matrix
        run: |
          tofu init -no-color -input=false
          tofu apply -no-color -input=false -lock-timeout=60m -auto-approve

      - uses: jwalton/gh-find-current-pr@master
        id: find_pr
        with:
          state: all

      - uses: peter-evans/create-or-update-comment@v4
        if: steps.find_pr.outputs.number
        env:
          RESULT_EMOJI: ${{ steps.apply.outcome == 'success' && '✅' || '⚠️' }}
        with:
          issue-number: ${{ steps.find_pr.outputs.number }}
          body: |
            ## ${{ env.RESULT_EMOJI }} `tofu apply` output pour `${{ matrix.directory }}`
            ```${{ steps.apply.outputs.stdout }}```
